---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  context:
    path: .
  args:
    path: args/
    optional: true
outputs:
  image:

params:
  CONTEXT:
  BUILD_ARGS_FILE:

caches:
  - path: cache

run: { path: build }
