---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: context
    path: .
outputs:
  - name: image

params:
  - name: CONTEXT
  - name: BUILD_ARGS_FILE

caches:
  - path: cache

run: { path: build }
