name: Publish Terragrunt 1.6.2 Image

on:
  push:
    paths:
      - "terragrunt/**"
      - ".github/workflows/publish-terragrunt_1.6.2-image.yml"
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/terragrunt

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU #emulation support with QEMU to be able to build against more platforms.
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the container to GitHub Container Registry using the latest tag
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: terragrunt/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            TOFU_VERSION=1.6.2
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:opentofu_v1.6.2
          push: true
          provenance: false
